### ISSUE TITLE
Add parsing timings

### ISSUE THREAD

**Issue by gnzlbg** [nst/JSONTestSuite#22]
It would be great if the test-suit could repeat each test until statistical significance is reached and report the timings with the standard deviations. 

This would allow to use the testsuite not only to asses the conformance and extensions support of a parser but also to asses the performance of the different parsers on corner cases.

**Comment by werediver** [comment]
It would be a nice feature, but performance-benchmarking seems like a slight off-topic for this tool.

I'd say that introduction of such a feature requires structural changes in the tool (splitting the source in multiple files, going OOP with all the encapsulation and separation of concerns) as a preparation step.

**Comment by nst** [comment]
Deciding how to benchmark parsing time can be quite arbitrary. Some parsers may be quicker for some kind of files, and some other for some other kind of files.

Also, the architecture is not ready to run reproductible benchmarks.

So, I prefer not to go into benchmarking and stick with the primary goal of this repo, which is to exhibit differences in parsing behaviour.
