### ISSUE TITLE
Jackson TestJSONParsing uses system default charset

### ISSUE THREAD

**Issue by jhorstmann** [nst/JSONTestSuite#5]
This probably causes the failure in `y_string_utf16.json`.

See use of the `String` constructor without specifying the charset, this uses the system default charset https://github.com/nst/JSONTestSuite/blob/master/parsers/test_java_jackson_2_8_4/TestJSONParsing.java#L36

The proper implementation would be to wrap the `byte[]` in a `ByteArrayInputStream` and pass this to the parser directly, which would allow it to figure out the encoding on it's own based on the first few bytes.

**Comment by mmastrac** [comment]
There is probably also an issue with `null` inputs - I added a special case to the `nanojson` driver to detect a testcase that should return `null`.

https://github.com/nst/JSONTestSuite/blob/master/parsers/test_java_nanojson_1_0/TestJSONParsing.java#L16
