### ISSUE TITLE
change y_object_duplicated_key to n_

### ISSUE THREAD

**Issue by rurban** [nst/JSONTestSuite#56]
http://seriot.ch/parsing_json.php#24
The RFC recommends to disallow duplicate keys "The names within an object should be unique."
SHOULD is either a n_ (fail with duplicates), or i_ (undefined), but never a y_ silently accept illegal JSON. 

See https://github.com/makamaka/JSON-PP/pull/30 and https://github.com/rurban/Cpanel-JSON-XS/pull/75

**Comment by nst** [comment]
RFC 7159 says:

1) "A JSON parser MUST accept all texts that conform to the JSON grammar."
2) "The names within an object SHOULD be unique."

RFC 2119 says:

3) "MUST - This word, or the terms "REQUIRED" or "SHALL", mean that the definition is an absolute requirement of the specification."
4) "SHOULD - This word, or the adjective "RECOMMENDED", mean that there may exist valid reasons in particular circumstances to ignore a particular item, but the full implications must be understood and carefully weighed before choosing a different course."

So, in my understanding, RFC 7159 recommends (2, 4) that JSON doesn't contain duplicated keys. This is an advice (and not a requirement) for JSON producers. The paragraph regarding JSON parsers requires (1, 3) that parsers accept all texts that conform to the grammar, and duplicated keys do conform to the grammar.

**Comment by rurban** [comment]
So you interpret SHOULD as silently allowing it, even if it SHOULD not be allowed. That's a stretch.
At least put it into `i_` and specify a recommendation which of the duplicate keys should be accepted, the first or the last, and if to warn or not on SHOULD violations.
It would be interesting to know which of the implementations chose first and last, and which silently accept duplicates and which do warn.

**Comment by nst** [comment]
I understand SHOULD as a recommendation, but not a requirement.

BTW, even if RFC had required keys to be unique, it still doesn't say what is "unique". Depending on the language and environment, strings comparison will use binary equivalence or normalized strings.

See [http://seriot.ch/json/transform.html](http://seriot.ch/json/transform.html) -> Strings for some striking differences.

**Comment by rabcyr** [comment]
I almost always understand SHOULD as being aimed at the producer of the data, and rarely ever the consumer.

On string comparison, interesting. For various Perl modules I just tested, '{"é":"NFC","é":"NFD"}' has unique keys.

**Comment by rurban** [comment]
This is the wrong move. The latest JSON RFC even added language for this behavior:
https://tools.ietf.org/html/rfc7159

"When the names within an object are not unique, the behavior of software that receives such an object is unpredictable.  Many implementations report the last name/value pair only.  Other implementations report an error or fail to parse the object, and some implementations report all of the name/value pairs, including duplicates."

And there's still "The names within an object SHOULD be unique."
So only _i or _n are valid, with _n being recommended.

**Comment by nst** [comment]
So, RFC 7159 **recommends** that object keys SHOULD be unique, but what if they are not?

RFC 7159 notes that, in practice, parsers handle duplicated keys in different ways.

I understand this as a warning for JSON producers, not as an freedom given to parsers to tell if duplicated keys is valid JSON or not.

Parsers still MUST accept all texts that conform to the JSON grammar.

That's why I'll keep the `_y` for now.
