### ISSUE TITLE
`n_object_pi_in_key_and_trailing_comma.json` does not contain PI as indicated

### ISSUE THREAD

**Issue by andreas-kupries** [nst/JSONTestSuite#78]
Also, is the `n`-indicator for the broken utf, or for the trailing comma ?

At offset 2 it contains a lone utf-8 continuation byte 185 (\271, 0b10'111'001)
```
hephaistos:(530) ~/Play/Marpa/WORK/src > ./tools/utf-viewer.tcl languages/json/tests/input/n/n_object_pi_in_key_and_trailing_comma.json 
[ 0] { 123 1 U+007b
[ 1] "  34 1 U+0022
[ 2] ¹ 185 0 ^
[ 3] "  34 1 U+0022
[ 4] :  58 1 U+003a
[ 5] "  34 1 U+0022
[ 6] 0  48 1 U+0030
[ 7] "  34 1 U+0022
[ 8] ,  44 1 U+002c
[ 9] } 125 1 U+007d
```

**Comment by nst** [comment]
Well, 185 is π, but in [Mac OS Roman](https://en.wikipedia.org/wiki/Mac_OS_Roman) Encoding.

But yes, the file name is not clear, so I renamed it into `n_object_lone_continuation_byte_in_key_and_trailing_comma.json`.

Also, the purpose of the test is not clear, but I want to keep the results collected by running all the parsers, so I'll just rename the file for now.

Thank you for spotting this.
