### ISSUE TITLE
Document:  utf8 or latin1 file encoding?

### ISSUE THREAD

**Issue by klahnakoski** [nst/JSONTestSuite#90]
What is the encoding for the test files? https://github.com/nst/JSONTestSuite/tree/master/test_parsing
Please add to main README.md

**Comment by nst** [comment]
There's no encoding specified. This is just raw bytes.

The goal is to assess JSON parsers behaviour.

While JSON parsers should expect UTF-8 content https://tools.ietf.org/html/rfc8259#section-8.1 some test files do contain accentuated characters encoded in Latin-1, or valid UTF-8 files, or invalid UTF-8 sequences.
